name: CI

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Clone main repository
      uses: actions/checkout@v2

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1
    - name: Set up NuGet
      uses: nuget/setup-nuget@v1
    - name: Install dependencies
      run: nuget restore USBHelperLauncher.sln

    - name: Build Solution
      run: msbuild USBHelperLauncher.sln -p:Configuration=Release -p:DebugType=none -p:DebugSymbols=false -p:AllowedReferenceRelatedFileExtensions=none

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: USBHelperLauncher
        path: USBHelperLauncher\bin\Release
